export { authAPI, userAPI } from './auth'
export { reviewAPI } from './review'
export { courseTableAPI } from './courseTable'
export { failRateAPI } from './failRate'
export { heroAPI } from './hero'
export { configAPI } from './config'
export { ossAPI } from './oss'
export { questionsAPI } from './questions'
export { notificationAPI } from './notification'
export { materialAPI } from './material'
export { systemAPI, statAPI } from './system'
export { pointsAPI } from './points'
export { dictionaryAPI } from './dictionary'
export { countdownAPI } from './countdown'
export { studyTaskAPI } from './studyTask'
export { pomodoroAPI } from './pomodoro'
export { gpaAPI } from './gpa'
