name: Build
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ['main']
    paths:
      - 'src/**'
      - 'config/**'
      - 'package.json'

  pull_request:
    branches: ['main']
    paths:
      - 'src/**'
      - 'config/**'
      - 'package.json'

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || (!github.event.pull_request.draft && !contains(github.event.pull_request.title, 'WIP'))
    strategy:
      matrix:
        node-version: ['22.x','24.x']

    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm run build:weapp
